version: '3.11'
services:

  web:
    build:
      context: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FFmpeg_PATH=/usr/local/bin/ffmpeg

  db:
    image: postgres:13   # Specify the version of the Postgres image
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      # POSTGRES_DB: myDB
      # POSTGRES_USER: test
      # POSTGRES_PASSWORD: test
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    # ports:
    #   - "5432:5432"  # Expose Postgres port

volumes:
  postgres_data:
    # driver: local