# Generated by Django 5.1.1 on 2024-09-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_title',
            new_name='title',
        ),
    ]
