# Generated by Django 5.1.1 on 2024-09-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_rename_video_title_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='language',
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='timestamp',
            field=models.DurationField(),
        ),
    ]
