# Generated by Django 5.1.1 on 2024-09-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_remove_subtitle_language_alter_subtitle_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='text',
            new_name='content',
        ),
    ]
